
package mx.omnitracs.maya.client.services.rest.sei.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.omnitracs.maya.client.services.rest.sei.ListVehicleActivityPositionResponseDTO;
import mx.omnitracs.maya.client.services.rest.sei.ObjectFactory;
import mx.omnitracs.maya.client.services.rest.sei.VehicleActivityAlertResponseDTO;
import mx.omnitracs.maya.client.services.rest.sei.VehicleActivityRequestDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVehicleActivityWebService", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVehicleActivityWebService {


    /**
     * 
     * @param request
     * @return
     *     returns mx.omnitracs.maya.client.services.rest.sei.VehicleActivityAlertResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeofenceVisits", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/", className = "mx.omnitracs.maya.client.services.rest.sei.GetGeofenceVisits")
    @ResponseWrapper(localName = "getGeofenceVisitsResponse", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/", className = "mx.omnitracs.maya.client.services.rest.sei.GetGeofenceVisitsResponse")
    public VehicleActivityAlertResponseDTO getGeofenceVisits(
        @WebParam(name = "request", targetNamespace = "")
        VehicleActivityRequestDTO request);

    /**
     * 
     * @param request
     * @return
     *     returns mx.omnitracs.maya.client.services.rest.sei.ListVehicleActivityPositionResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPositions", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/", className = "mx.omnitracs.maya.client.services.rest.sei.GetPositions")
    @ResponseWrapper(localName = "getPositionsResponse", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/", className = "mx.omnitracs.maya.client.services.rest.sei.GetPositionsResponse")
    public ListVehicleActivityPositionResponseDTO getPositions(
        @WebParam(name = "request", targetNamespace = "")
        VehicleActivityRequestDTO request);

    /**
     * 
     * @param request
     * @return
     *     returns mx.omnitracs.maya.client.services.rest.sei.VehicleActivityAlertResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAlerts", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/", className = "mx.omnitracs.maya.client.services.rest.sei.GetAlerts")
    @ResponseWrapper(localName = "getAlertsResponse", targetNamespace = "http://sei.rest.services.client.maya.omnitracs.mx/", className = "mx.omnitracs.maya.client.services.rest.sei.GetAlertsResponse")
    public VehicleActivityAlertResponseDTO getAlerts(
        @WebParam(name = "request", targetNamespace = "")
        VehicleActivityRequestDTO request);

}
