
package mx.omnitracs.maya.client.services.rest.sei.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleActivityWebServiceService", targetNamespace = "http://impl.sei.rest.services.client.maya.omnitracs.mx/", wsdlLocation = "http://10.88.12.141/customer-services/VehicleActivityService?wsdl")
public class VehicleActivityWebServiceService
    extends Service
{

    private final static URL VEHICLEACTIVITYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLEACTIVITYWEBSERVICESERVICE_EXCEPTION;
    private final static QName VEHICLEACTIVITYWEBSERVICESERVICE_QNAME = new QName("http://impl.sei.rest.services.client.maya.omnitracs.mx/", "VehicleActivityWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.88.12.141/customer-services/VehicleActivityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLEACTIVITYWEBSERVICESERVICE_WSDL_LOCATION = url;
        VEHICLEACTIVITYWEBSERVICESERVICE_EXCEPTION = e;
    }

    public VehicleActivityWebServiceService() {
        super(__getWsdlLocation(), VEHICLEACTIVITYWEBSERVICESERVICE_QNAME);
    }

    public VehicleActivityWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLEACTIVITYWEBSERVICESERVICE_QNAME, features);
    }

    public VehicleActivityWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, VEHICLEACTIVITYWEBSERVICESERVICE_QNAME);
    }

    public VehicleActivityWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLEACTIVITYWEBSERVICESERVICE_QNAME, features);
    }

    public VehicleActivityWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleActivityWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVehicleActivityWebService
     */
    @WebEndpoint(name = "VehicleActivityWebServicePort")
    public IVehicleActivityWebService getVehicleActivityWebServicePort() {
        return super.getPort(new QName("http://impl.sei.rest.services.client.maya.omnitracs.mx/", "VehicleActivityWebServicePort"), IVehicleActivityWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVehicleActivityWebService
     */
    @WebEndpoint(name = "VehicleActivityWebServicePort")
    public IVehicleActivityWebService getVehicleActivityWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.sei.rest.services.client.maya.omnitracs.mx/", "VehicleActivityWebServicePort"), IVehicleActivityWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLEACTIVITYWEBSERVICESERVICE_EXCEPTION!= null) {
            throw VEHICLEACTIVITYWEBSERVICESERVICE_EXCEPTION;
        }
        return VEHICLEACTIVITYWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
